[package]
name = "proto"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11.7"
serde = { version = "1.0.152", features = ["derive"] }

[build-dependencies]
color-eyre = "0.6.2"
prost-build = "0.11.7"
